# Generated by Django 5.2 on 2025-05-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('version', models.FloatField(default=0)),
                ('is_installed', models.BooleanField(default=False)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('last_upgraded', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'permissions': [('install_moduleregistry', 'Can install module'), ('uninstall_moduleregistry', 'Can uninstall module'), ('upgrade_moduleregistry', 'Can upgrade module')],
            },
        ),
    ]
